version: "3.8"

services:
  cloudflare-tunnel:
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    depends_on:
      - web-app

  web-app:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./Dockerfile
    volumes:
      - ../__data/:/app/__data
